spring:
  application:
    name: transactions-api
    
server:
  port: 8081

cassandra:
  contactpoints: localhost,127.0.0.1
  port: 9042 
  keyspace: transactions
  
logging:
  config: config/log4j2-console.xml
      
      