spring:
  application:
    name: transactions-api
    
server:
  port: 8081

management:
  server:
    port: 9002
  
cassandra:
  contactpoints: localhost,127.0.0.1
  port: 9043 
  keyspace: transactions
  
logging:
  config: config/log4j2-console.xml
      
      