spring:
  application:
    name: cassandra-client
    
server:
  port: 8080

management:
  server:
    port: 9001
    
cassandra:
  contactpoints: localhost,127.0.0.1
  port: 9042 
  keyspaces: accounts, transactions   
  
logging:
  config: config/log4j2-console.xml
      
      