spring:
  application:
    name: cassandra-client
    
cassandra:
  contactpoints: localhost,127.0.0.1
  port: 9042 
  keyspaces: accounts, transactions   
  
logging:
  config: config/log4j2-console.xml
  level:
    com.datastax.driver.core.ClockFactory: OFF
      
      